Client.php

Split flattening arguments into separate recursive method
Instead of testing for command name (mset, msetnx and hmset) checking for numeric array key to decide whether to add it as an argument or not.
Fixed the problems I had in standalone mode. Not excessively tested with php-redis extension

Fix for issue #38; option array with standalone mode

---

Client.php
tests/CredisTest.php

Two fixes;
Fixed zrangebyscore not working when providing the options 'withscores' and/or 'limit' while using the phpRedis extension,  by reformatting the argument array before passing it to phpRedis.
> Warning: Redis::zRangeByScore() expects at most 4 parameters, 6 given
Fixed the return value for zrangebyscore  when using 'withscores' in standalone mode to be the same as phpRedis; The array key is the item and it's value the score.

Fixed zrangebyscore for phpRedis

---

Client.php
tests/CredisTest.php

I made a boo-boo with the 'withscores' option. Credis now expects another inputformat than the php-redis extension does. I fixed this by adding my workaround in the standalone mode instead, so Credis and php-redis are interchangeable.
This is a breaking change though, and will break implementations using 'withscores' since pull request #44 was merged. But I hope you consider 'fixing' this inconsistency.

Arguments for zrangebyscore to be equal to php-redis

---

Cluster.php

Hi there. Thank you for the neat library!
I'm using a Redis cluster with Sentinel and here what I've found:
```
$sentinel = new Credis_Sentinel(new Credis_Client('127.0.0.1',26379));
$masterAddress = $sentinel->getMasterAddressByName('mymaster');
$cluster = $sentinel->getCluster('mymaster'); // - right here that cluster will use one of the slave client.
$cluster->select(6); // -- we want to use 6-th database
$cluster->get('test'); // Cluster will read from 6-th database which was selected on slave's $client after creation, everything is ok :-)
$cluster->set('test', '123'); // - right here cluster will write to master but master's $selectedDb is on zero database. Oops.
```
So without this commit all the data goes into default (zero) database.
With this commit all data goes to separate …

Use correct database for every client in cluster.

---

Client.php
tests/CredisTest.php

Hi
I had a problem with last code's hscan and I fixed that problem
hscan is different from other scans it must have a field too, you can read end of scan's documentation for more details.
I don't know about zscan and sscan but I know last code about hscan was wrong and it caused exception with message `invalid cursor` and it's because of wrong command:
```
127.0.0.1:6379[1]> hscan 0 match qti3e.*
(error) ERR invalid cursor
127.0.0.1:6379[1]> hscan users 0 match qti3e.*
1) "0"
2) 1) "qti3e.fname"
2) "Alireza"
3) "qti3e.lname"
4) "Ghadimi"
5) "qti3e.email"
6) "qti3eqti3e@gmail.com"
127.0.0.1:6379[1]>
```

Debug hscan

---

Client.php
tests/CredisTest.php

- Remove php +5.4 array construction.
- Fix scan in standalone mode, it was truncating results or returning an array in an array.
- Fix sscan and zscan as they where missing an argument.
- Ensure phpredis mode works with hscan/sscan/zscan.
- requires arguments in a different order, swapping them in the custom function is the most-sane way to swap the reference around.
- Ensures that the iterator reference is updated in standalone mode, as redis is permitted to return empty arrays. Only when the iterator returns zero is there nothing left.
- Added tests for basic usage of all the functions.

Update hscan/sscan/zscan/scan, Fix compatibility with phpredis

---

Client.php

With Cm_Cache_Backend_Redis supporting having initial sentinel support, reporting which host failed to connect is now useful

Include host:port in the connection error message

---

Client.php

There is a test for mget in standalone mode but it is broken.
At some stage I'll look into setting up Travis-ci or similar for build tests

Ignore keys for mget like phpredis does.

---

Client.php
tests/CredisTest.php

The sscan, hscan and zscan methods all take 4 arguments:
iterator
field
pattern
count
They simply wrap the __call function with the appropriate redis method
name. Count is always passed as 4th element in the argument array, eg:
$args[3].
The code in __call will check for a non-empty value in $args[3], and
then use $args[4] as the value for COUNT. As $args[4] can never be set,
this is always null, and causes an array reference warning, as well as
a syntax error with the sscan/hscan/zscan method.
This update takes the count value from $args[3], where it is set by the
wrapper methods.
Additionally, the tests have been updated to include a count so that
this kind of issue will be picked up in the future if there are any
regressions.

Allow count to be used in sscan, hscan and zscan

---

Client.php

This is a silly change that fixes HHVM throwing up with the following error if no explicit timeout was set:
Fatal error: Uncaught TypeError: Argument 5 passed to fsockopen() must be an instance of float, null given in /vendor/colinmollenhour/credis/Client.php:441

HHVM Compat: Do not pass null timeout value to connect() or pconnect()

---

Client.php
tests/CredisTest.php

hmset's 2nd argument is an array of key/value pairs. The key can be integers, so needs special handling vs just using _flattenArguments

Fix standalone mode hMSet

---

Client.php

- Handle is an application convert a php error into an Exception 
- per https://github.com/colinmollenhour/credis/issues/76 the connection can get into an unknowable state in the event of a read-timeout. The safe solution is to close the connection and cleanup the library state so a re-connection can be safely done.
- A persistent socket which has a read-timeout can leave data to be read across requests, which is obviously deeply undesirable.  should be closed in the event of an error to remove any errors from a previous use of that socket.

Improve retry logic

---

.travis.yml

phpredis 3.1.4 has been released as stable, so non of the tests should fail now.

Update unit tests for phpredis 3.1.4

---

Client.php

The native redis client expects that the iterator variable will be passed by reference, not value.  Without this change you will receive the following error if you attempt to us the scan family of commands:
PHP Error[2]: Parameter 1 to Redis::scan() expected to be a reference, value given
in file /usr/local/eti_deploy/releases/4/vendor/colinmollenhour/credis/Client.php at line 1139

Fix scan commands when using native php extension redis client.

---

.gitignore
phpunit_local.sh
testenv/docker-compose.yml
testenv/env/php-5.5/Dockerfile
testenv/env/php-5.6/Dockerfile
testenv/env/php-7.0/Dockerfile
testenv/env/php-7.1/Dockerfile
testenv/env/php-7.2/Dockerfile

Script phpunit_local.sh runs unit tests locally in environment similar to Travis-CI
It runs tests in different PHP versions with suitable PHPUnite version.
You can see results of unit tests execution in console.
Also all execution logs are saved to files phpunit_<date-time>.log
Prerequisites for running unit tests on local machine:
- docker
- docker-compose
You can find definition of all test environments in folder testenv/
This folder is not automatically synced with .travis.yml
If you add new PHP version to .travis.yml then you'll need to adjust files in testenv/

Add script for running unit tests locally

---

.gitignore
.travis.yml
testenv/env/php-7.2/Dockerfile

Travis config changes:
- Switch travis config to matrix
- Install phpunit via composer
- PHP 7.2: Fix version of PHPUnit to 7.5
Local php env
- PHP 7.2: Change version of PHPUnit to 7.5

Switch unit tests PHP 7.2 environment to PHPUnit 7.5

---

Client.php
README.markdown
tests/CredisTest.php

Use standalone PHP driver because PHP Redis extension doesn't work with TLS.
Syntax `$redis = new Credis_Client('tls://host[:port][/persistence_identifier]')`

Enable encrypted connections with TLS

---

Client.php

to follow the documented order,
reverse order is deprecated from php 7.4 on

change argument order of implode

---

Client.php

This PR adds the `Credis_Client::VERSION` constant. It will need to be bumped for every release.
Closes #135.

Add Credis_Client::VERSION constant

---

.travis.yml
Client.php
testenv/docker-compose.yml
testenv/env/php-5.6/Dockerfile
testenv/env/php-7.0/Dockerfile
testenv/env/php-7.1/Dockerfile
testenv/env/php-7.2/Dockerfile
testenv/env/php-7.3/Dockerfile
testenv/env/php-7.4/Dockerfile
tests/CredisClusterTest.php
tests/CredisSentinelTest.php
tests/CredisTest.php
tests/CredisTestCommon.php

Fixes #140 
- Removed PHP 5.5 & Added PHP 7.4
- Update php-redis to 5.3.0
- Update redis-server to 6.0.8
- Fixes AUTH may not cleanup last error
- Fixes AUTH error message changed since Redis v6

Fixes #140: Update test suites

---

.travis.yml
Client.php
tests/CredisTest.php

- make downloaded redis-server PATH priority higher then built-in one
- Fixes port always be 6379 even no port specified in host string and specified the port number other then 6379 in constructor
- Fixes persistent too
- Added test cases

Fixes connectionStrings parsing

---

.gitignore
Client.php
composer.json
tests/CredisStandaloneTest.php
tests/CredisTest.php

phpredis connect's port is int and doesn't actually accept nulls, 0 is the documented value for unix connection strings, even for older versions
Should fix #159

php8.1 compat fix for socket connection strings & phpredis

---

Client.php

Switch to php 5.6+ compatible syntax for `_prepare_command` function.

php 8.2 compatibility update

---

Client.php

Close #172
Use "\r\n" directly instead of `define("CRLF")`

Use const keyword instead of define function for CRLF

---

.github/workflows/ci.yml
.gitignore
.php-cs-fixer.dist.php
Client.php
Cluster.php
Module.php
Sentinel.php
tests/CredisClusterTest.php
tests/CredisSentinelTest.php
tests/CredisStandaloneClusterTest.php
tests/CredisStandaloneSentinelTest.php
tests/CredisStandaloneTest.php
tests/CredisTest.php
tests/CredisTestCommon.php
tests/phpunit-shims/php7.php
tests/phpunit-shims/php8.php

Close #173
I think the reformatting will improve the code's readability and maintainability.
* Use php-cs-fixer to re-format the code. 
* Remove unused (incorrect) consts: Credis_Client::VERSION, Credis_Client::FREAD_BLOCK_SIZE
* Update the comment of Credis_Client __construct: "Creates a Redisent connection" -> "Creates a connection" because there is no Redisent object anymore in code.
ps: feel free to edit on the PR directly
Diff without spaces: https://github.com/colinmollenhour/credis/pull/175/files?diff=split&w=1

Reformat code, update comment of Credis_Client __construct

---

Client.php
tests/CredisTest.php

mget behaves differently between credis/phpredis when given an empty array. Smoothed that over and added a test for that.

Smooth over mget quirks between credis/phpredis modes

---

.editorconfig
.gitattributes
Client.php
tests/CredisTest.php

- Fixes type hinting on for `scan`/`sscan`/`zscan`/`hscan `
- Aligns behavior of `scan`/`sscan`/`zscan`/`hscan` with phpredis of how an empty/falsy iterator is handled.
- Fix errors in `exec()` could cause the redis connection and credis internal state to become out of sync
- Prevent `scan`/`sscan`/`zscan`/`hscan` from being used in `pipeline`/`multi` mode, as phpredis would cause trigger a fatal php error instead of throwing an exception in this case
- Fix calling `mget([])` in standalone mode didn't match phpredis mode
- Fix `multi` mode failing when commands where issued between `multi()` and `pipeline()`. Recommended usage is however `pipeline()-> multi()->...->exec()`
This breaks pipeline mode for these functions as they return early, but mget was already doing this. Documented in …

Fixes for scan/sscan/zscan/hscan & transaction/multi handling

---

Client.php

Hi,
Using Magento 2.4.6-p2 open source and colinmollenhour/credis v1.16.0. Using a command line script I am getting this error:
PHP Warning: Trying to access array offset on value of type bool in colinmollenhour/credis/Client.php on line 1156
Not sure why this is happening. Have not debugged in depth, but
$execResponse = array_pop($response);
is actually false, so doing:
if(!empty($execResponse))
{
foreach ($queuedResponses as $key => $command) {
list($name, $arguments) = $command;
$response[] = $this->decode_reply($name, $execResponse[$key], $arguments);
}    
}
suppresses the warning.
Michael.

Fix for warning Trying to access array offset on value of type bool

---

Cluster.php

Need to declare this variable on top on PHP version 3 or we will get the warning: Deprecated: Creation of dynamic property Credis_Cluster::$replicas is deprecated in vendor/colinmollenhour/credis/Cluster.php on line 86

Update Cluster.php to fix issue with PHP version 8.3
